"""V2.52: the whole pipeline, every layer permutation, every paraphrase condition.

WHY ONE GRID
------------
Every layer in this programme was measured against the condition it was designed for, in
isolation. That is how each one earned its place, and it is also how a pipeline quietly
acquires layers that help alone and interfere together. This runs all of them at once.

THE TWO OPTIONAL LAYERS ARE COMPLEMENTARY BY CONSTRUCTION, WHICH IS THE THING TO TEST.
There are two independent ways the organizer could reword a message:

    TEMPLATE paraphrase    the wrapper is reworded, the values are intact
                           "I'm looking for X. A key requirement is: cotton."
                           -> "Show me X -- it has to be cotton."
    ATTRIBUTE paraphrase   the wrappers are intact, the values are reworded
                           -> "I'm looking for X. A key requirement is: a soft plant fibre."

They defeat different machinery and are handled by different layers. The BERT scaffolding
tagger fires only on messages the recognition gate does not know, so it addresses TEMPLATE
paraphrase. The LLM deparaphraser fires only where a VALUE is catalogue-unattested, so it
addresses ATTRIBUTE paraphrase. Neither can help with the other's case, and BOTH is the
condition where each has to work while the other is also failing.

ARMS
  V1 baseline    deterministic only: tagger off, span node off, deparaphraser off
  +BERT          scaffolding tagger ONLY         -- deliberately the incomplete half
  +SPAN          span node ONLY, no tagger       -- prices the tagger's 254 MB
  +BERT+SPAN     tagger plus exact 1-3 token dictionary and category recovery
                                                 -- the TEMPLATE handler, complete
  +LLM           deparaphraser only              -- the ATTRIBUTE handler
  V2 full        all four on

WHY +SPAN ALONE IS AN ARM. The tagger costs 254 MB and, measured in isolation, moves the
template condition by +0.0024 against a -0.287 gap. A span-node-only audit found the
dictionary lookup carries the entire recall story on its own -- value recall 1.0000 without
the tagger against 0.9992 with it, the tagger costing a hair of recall by occasionally
stripping a token the lookup needed. Its whole measured contribution was one cell:
spurious attributes on `plain_opening`, 0.125 -> 0.000.

So the open question is whether 254 MB buys anything end to end. `+BERT+SPAN` minus `+SPAN`
answers it. If that difference is near zero the tagger can be dropped and the submission
falls from ~254 MB to essentially the 708 KB dictionary.

WHY +BERT IS KEPT AS ITS OWN ARM EVEN THOUGH IT IS KNOWN TO BE INSUFFICIENT. The tagger
retains 99.25% of canonical constraint slots and then hands them to a miner that recovered
0.00% of SHORT constraints, because mining is built for distinctive multi-word phrases and
a one-to-three token value is far too common to survive its df filter. Measured on an
earlier version of this grid, the tagger alone moved the template condition by +0.00315
against a -0.287 gap. Keeping it as a separate arm makes that visible rather than letting
the combined arm take credit for it.

CONDITIONS. Four of the five share one session base, so their deltas are directly
comparable rather than merely adjacent numbers.

  official200    the released public set, clean
  unseen800      review800 canonical replay -- the SAME materialisation the paraphrase
                 conditions use, with nothing rewritten. This is the control, and using
                 the raw session file instead would confound materialisation with
                 paraphrasing.
  template       unseen800 + wrapper rewording from the held-out template bank
  attribute      the open-vocabulary suite: 204 independently generated paraphrases over
                 the same targets, generated by a DIFFERENT model family than the solver
  both           attribute + wrapper rewording, composed

WHAT IS DELIBERATELY ABSENT. Two layers were built, measured and rejected, and their
absence is a result rather than an omission:

  retrieval augmentation   giving the deparaphraser retrieved candidates scored BELOW
                           doing nothing (-0.0050 against the suppression floor); told
                           candidates were optional hints, the model still answered
                           off-list only 2 times in 21
  node 5 NLI verification  0.8349 AUROC in isolation, but no threshold transferred: it
                           discarded 76% of CORRECT proposals on open vocabulary and cut
                           the gain from +0.0169 to +0.0009

HOW TO READ IT. official200 and unseen800 are the decision criteria -- the organizer
confirmed no paraphrasing, so the three paraphrase columns are characterisation and cannot
license a regression on the first two. The question the grid answers that no isolated run
could: does V2 full beat max(+BERT, +LLM) on `both`, or do the layers interfere?

Run:  PYTHONIOENCODING=utf-8 python -u robustness/v2/evaluate_full_pipeline.py
"""
from __future__ import annotations

import importlib.util as ilu
import json
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
V2 = ROOT / "robustness" / "v2"
OV = V2 / "open_vocabulary"
OUT = V2 / "results" / "full_pipeline_v2_52.json"

_s = ilu.spec_from_file_location("_stress", ROOT / "experiments" / "scripts"
                                 / "31_paraphrase_stress.py")
_stress = ilu.module_from_spec(_s)
_s.loader.exec_module(_stress)

_t = ilu.spec_from_file_location("_tmpl", V2 / "run_official_template_paraphrase.py")
_tm = ilu.module_from_spec(_t)
_t.loader.exec_module(_tm)


def main() -> None:
    os.environ["LLM_RERANK"] = "0"
    os.environ["LLM_EXTRACT"] = "0"
    os.environ.setdefault("LLM_RESOLVE_CACHE",
                          str(OV / ".pipeline_resolve_cache.json"))
    from evaluator.local_evaluator import catalog_index, evaluate, load_jsonl
    from submission.agent import Agent
    from submission.bert_extract import ScaffoldingTagger
    from submission.llm_resolve import LLMResolver

    cid, cats, prods = catalog_index(ROOT / "data" / "catalog.jsonl")
    base = Agent(ROOT / "data" / "catalog.jsonl")
    transform = _tm.transform(_tm.bank())

    conditions = {
        "official200": (load_jsonl(ROOT / "data" / "public_set.jsonl"), False),
        "unseen800": (load_jsonl(OV / "review800_canonical_replay.jsonl"), False),
        "template": (load_jsonl(OV / "review800_canonical_replay.jsonl"), True),
        "attribute": (load_jsonl(OV / "review800_open_vocab_paraphrase.jsonl"), False),
        "both": (load_jsonl(OV / "review800_open_vocab_paraphrase.jsonl"), True),
    }
    # (label, tagger, span node, deparaphraser, route node)
    #
    # ROUTE IS A CONTROLLED DIMENSION. Node 1 lives on the base Agent, so leaving it on
    # would make "V1 baseline" not a baseline at all -- every arm would silently include
    # it and its contribution would be invisible.
    ARMS = (("V1 baseline", False, False, False, False),
            ("+ROUTE", False, False, False, True),
            ("+SPAN", False, True, False, False),
            ("+ROUTE+SPAN", False, True, False, True),
            ("V2 full", True, True, False, True))

    # One resolver shared across every arm and condition, so its cache is warm and the
    # grid does not pay 200 API calls per cell. Behaviour per call is identical either way.
    #
    # LLM_RESOLVE MUST BE SET BEFORE CONSTRUCTION. `LLMResolver.__init__` latches the flag,
    # so building this before the arm loop set the variable produced a permanently disabled
    # resolver and a grid in which the +LLM rows were silently identical to the baseline.
    # Per-arm gating is done by attaching or detaching the object, not by the env var.
    # A run with no LLM arm selected makes no network call, so it is exactly reproducible
    # and must not be blocked by the resolver guard below.
    _sel = os.environ.get("PIPELINE_ARMS", "").strip()
    _keep = {x.strip() for x in _sel.split(",")} if _sel else None
    needs_llm = any(a[3] and (_keep is None or a[0] in _keep) for a in ARMS)
    route = base.route_node
    if route is None:
        print("route node unavailable -- refusing to run a grid whose +ROUTE arms would")
        print("be silently identical to their non-route counterparts.")
        return
    os.environ["LLM_RESOLVE"] = "1" if needs_llm else "0"
    shared = LLMResolver().bind(base.ix.df)
    if needs_llm and not shared.enabled:
        print("resolver not enabled -- is GROQ_API_KEY set? refusing to run a grid whose")
        print("+LLM arms would be silently identical to the baseline.")
        return
    if not needs_llm:
        print("no LLM arm selected: this run is OFFLINE and exactly reproducible\n")

    span = base.span_node
    if span is None or not span.ok:
        print("span node unavailable -- refusing to run a grid whose +SPAN arms would be")
        print("silently identical to +BERT.")
        return

    def make(bert: bool, use_span: bool, llm: bool, use_route: bool):
        a = object.__new__(Agent)
        a.ix, a.sessions = base.ix, {}
        a.llm = a.llm_extract = None
        os.environ["BERT_EXTRACT"] = "1" if bert else "0"
        a.tagger = ScaffoldingTagger() if bert else None
        a.span_node = span if use_span else None
        a.resolver = shared if llm else None
        a.route_node = route if use_route else None
        return a

    # Arm subsetting, so a rerun forced by ONE broken arm does not re-pay for the arms
    # that were already valid. The baseline is always kept: every delta is against it.
    only = os.environ.get("PIPELINE_ARMS", "").strip()
    if only:
        keep = {x.strip() for x in only.split(",")} | {"V1 baseline"}
        ARMS = tuple(a for a in ARMS if a[0] in keep)
        print(f"arms restricted to: {', '.join(a[0] for a in ARMS)}")
        print()

    print(f"{'arm':<14}" + "".join(f"{c:>13}" for c in conditions))
    print("-" * (14 + 13 * len(conditions)))
    t0, table = time.time(), {}
    for label, bert, use_span, llm, use_route in ARMS:
        row = {}
        for name, (samples, warp) in conditions.items():
            agent = make(bert, use_span, llm, use_route)
            if warp:
                r = _stress.evaluate_transformed(agent, samples, cid, cats, prods,
                                                 transform)
            else:
                r = evaluate(agent, samples, cid, cats, prods)
            row[name] = {
                "score": round(r["recommended_technical_score"], 6),
                "hr10": round(r["hit_rate_at_10"], 4),
                "mrr": round(r["mrr"], 4),
                "mttc": round(r["mttc"], 3),
            }
        table[label] = row
        print(f"{label:<14}" + "".join(f"{row[c]['score']:>13.6f}" for c in conditions),
              flush=True)
    shared.flush()

    ref = table["V1 baseline"]
    print(f"\ndeltas vs V1 baseline")
    print(f"{'arm':<14}" + "".join(f"{c:>13}" for c in conditions))
    print("-" * (14 + 13 * len(conditions)))
    for label in [x for x in ("+ROUTE", "+SPAN", "+ROUTE+SPAN", "V2 full")
                  if x in table]:
        print(f"{label:<14}" + "".join(
            f"{table[label][c]['score'] - ref[c]['score']:>+13.6f}" for c in conditions))

    print(f"\n{'arm':<14}{'condition':<14}{'HR@10':>9}{'MRR':>9}{'MTTC':>9}")
    print("-" * 55)
    for label in table:
        for c in conditions:
            d = table[label][c]
            print(f"{label:<14}{c:<14}{d['hr10']:>9.4f}{d['mrr']:>9.4f}{d['mttc']:>9.3f}")

    # INTERFERENCE. The one question no isolated run could answer.
    print("\n  do the two layers interfere?")
    print(f"  {'condition':<14}{'best single':>13}{'V2 full':>11}{'V2 - best':>12}")
    print("  " + "-" * 50)
    for c in ([] if "V2 full" not in table else conditions):
        best = max(table.get("+ROUTE+SPAN", ref)[c]["score"], table.get("+SPAN", ref)[c]["score"])
        full = table["V2 full"][c]["score"]
        print(f"  {c:<14}{best:>13.6f}{full:>11.6f}{full - best:>+12.6f}")
    print("  A negative last column means the layers INTERFERE: the pipeline is worse than")
    print("  its better half. Positive means they compose.")

    if "+SPAN" in table and "+ROUTE+SPAN" in table:
        print("\n  what does the tagger's 254 MB buy on top of the span node?")
        print(f"  {'condition':<14}{'+SPAN':>11}{'+ROUTE+SPAN':>13}{'route delta':>14}")
        print("  " + "-" * 52)
        for c in conditions:
            a, b = table["+SPAN"][c]["score"], table["+ROUTE+SPAN"][c]["score"]
            print(f"  {c:<14}{a:>11.6f}{b:>13.6f}{b - a:>+14.6f}")
        print("  Node 1 ALONE is slightly negative; it only pays beside the span node.")
        print("  Routing protects evidence, and without extraction there is little to")
        print("  protect -- clearing rejections and skipping no-evidence turns matters")
        print("  only once the span node is actually recovering values.")

    dec = ("official200", "unseen800")
    worst = min(table.get("V2 full", ref)[c]["score"] - ref[c]["score"] for c in dec)
    print(f"\n  worst decision-criterion delta for V2 full: {worst:+.6f}")
    print(f"  ({', '.join(dec)} are the decision criteria; the organizer confirmed no")
    print("   paraphrasing, so the paraphrase columns are characterisation only.)")
    print(f"\n  resolver:  {json.dumps(shared.stats())}")
    print(f"  span node: {json.dumps(span.stats())}")
    print(f"  route node: {json.dumps(route.stats())}")
    print(f"  {time.time() - t0:.0f}s")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(
        {"experiment": "V2.52 full pipeline grid", "arms": table,
         "conditions": list(conditions), "resolver": shared.stats(),
         "span_node": span.stats(),
         "worst_decision_delta_v2_full": round(worst, 6)},
        indent=2) + "\n", encoding="utf-8")
    print(f"[saved] {OUT}")


if __name__ == "__main__":
    main()
